/**
 * JavaScript code to detect available availability of a
 * particular font in a browser using JavaScript and CSS.
 *
 * Author : Lalit Patel
 * Website: http://www.lalit.org/lab/javascript-css-font-detect/
 * License: Apache Software License 2.0
 *          http://www.apache.org/licenses/LICENSE-2.0
 * Version: 0.15 (21 Sep 2009)
 *          Changed comparision font to default from sans-default-default,
 *          as in FF3.0 font of child element didn't fallback
 *          to parent element if the font is missing.
 * Version: 0.2 (04 Mar 2012)
 *          Comparing font against all the 3 generic font families ie,
 *          'monospace', 'sans-serif' and 'sans'. If it doesn't match all 3
 *          then that font is 100% not available in the system
 * Version: 0.3 (24 Mar 2012)
 *          Replaced sans with serif in the list of baseFonts
 */

/**
 * Usage: d = new Detector();
 *        d.detect('font name');
 */
var Detector = function() {
    // a font will be compared against all the three default fonts.
    // and if it doesn't match all 3 then that font is not available.
    var baseFonts = ['monospace', 'sans-serif', 'serif'];

    // we use m or w because these two characters take up the maximum width.
    // And we use a LLi so that the same matching fonts can get separated
    var testString = "mmmmmmmmmmlli";

    //we test using 72px font size, we may use any size. I guess larger the better.
    var testSize = '72px';

    var h = document.getElementsByTagName("body")[0];

    // create a SPAN in the document to get the width of the text we use to test
    var s = document.createElement("span");
    s.style.fontSize = testSize;
    s.innerHTML = testString;
    var defaultWidth = {};
    var defaultHeight = {};
    for (var index in baseFonts) {
        //get the default width for the three base fonts
        s.style.fontFamily = baseFonts[index];
        h.appendChild(s);
        defaultWidth[baseFonts[index]] = s.offsetWidth; //width for the default font
        defaultHeight[baseFonts[index]] = s.offsetHeight; //height for the defualt font
        h.removeChild(s);
    }

    function detect(font) {
        var detected = false;
        for (var index in baseFonts) {
            s.style.fontFamily = font + ',' + baseFonts[index]; // name of the font along with the base font for fallback.
            h.appendChild(s);
            var matched = (s.offsetWidth != defaultWidth[baseFonts[index]] || s.offsetHeight != defaultHeight[baseFonts[index]]);
            h.removeChild(s);
            detected = detected || matched;
        }
        return detected;
    }

    this.detect = detect;
};

var fonts = [];
var results = [];
var d = new Detector();
/**
 * other stuff
 */
 
// function font_init() {
//     // fonts.push("cursive");
//     // fonts.push("monospace");
//     // fonts.push("serif");
//     // fonts.push("sans-serif");
//     // fonts.push("fantasy");
//     // fonts.push("default");
//     // fonts.push("Arial");
//     // fonts.push("Arial Black");
//     // fonts.push("Arial Narrow");
//     // fonts.push("Arial Rounded MT Bold");
//     // fonts.push("Bookman Old Style");
//     // fonts.push("Bradley Hand ITC");
//     // fonts.push("Century");
//     // fonts.push("Century Gothic");
//     // fonts.push("Comic Sans MS");
//     // fonts.push("Courier");
//     // fonts.push("Courier New");
//     // fonts.push("Georgia");
//     // fonts.push("Gentium");
//     // fonts.push("Impact");
//     // fonts.push("King");
//     // fonts.push("Lucida Console");
//     // fonts.push("Lalit");
//     // fonts.push("Modena");
//     // fonts.push("Monotype Corsiva");
//     // fonts.push("Papyrus");
//     // fonts.push("Tahoma");
//     // fonts.push("TeX");
//     // fonts.push("Times");
//     // fonts.push("Times New Roman");
//     // fonts.push("Trebuchet MS");
//     // fonts.push("Verdana");
//     // fonts.push("Verona");
//     // BEGIN Mac OS X Fonts - http://en.wikipedia.org/wiki/List_of_typefaces_included_with_OS_X
//     fonts.push("Al Bayan");
//     fonts.push("American Typewriter");
//     fonts.push("Andale Mono");
//     fonts.push("Apple Casual");
//     fonts.push("Apple Chancery");
//     fonts.push("Apple Garamond");
//     fonts.push("Apple Gothic");
//     fonts.push("Apple LiGothic");
//     fonts.push("Apple LiSung");
//     fonts.push("Apple Myungjo");
//     fonts.push("Apple Symbols");
//     fonts.push("AquaKana");
//     fonts.push("Arial");
//     fonts.push("Arial Hebrew");
//     fonts.push("Ayuthaya");
//     fonts.push("Baghdad");
//     fonts.push("Baskerville");
//     fonts.push("Beijing");
//     fonts.push("BiauKai");
//     fonts.push("Big Caslon");
//     fonts.push("Brush Script");
//     fonts.push("Chalkboard");
//     fonts.push("Chalkduster");
//     fonts.push("Charcoal");
//     fonts.push("Charcoal CY");
//     fonts.push("Chicago");
//     fonts.push("Cochin");
//     fonts.push("Comic Sans");
//     fonts.push("Cooper");
//     fonts.push("Copperplate");
//     fonts.push("Corsiva Hebrew");
//     fonts.push("Courier");
//     fonts.push("Courier New");
//     fonts.push("DecoType Naskh");
//     fonts.push("Devanagari");
//     fonts.push("Didot");
//     fonts.push("Euphemia UCAS");
//     fonts.push("Fang Song");
//     fonts.push("Futura");
//     fonts.push("Gadget");
//     fonts.push("Geeza Pro");
//     fonts.push("Geezah");
//     fonts.push("Geneva");
//     fonts.push("Geneva CY");
//     fonts.push("Georgia");
//     fonts.push("Gill Sans");
//     fonts.push("Gujarati");
//     fonts.push("Gung Seoche");
//     fonts.push("Gurmukhi");
//     fonts.push("Hangangche");
//     fonts.push("HeadlineA");
//     fonts.push("Hei");
//     fonts.push("Helvetica");
//     fonts.push("Helvetica CY");
//     fonts.push("Helvetica Neue");
//     fonts.push("Herculanum");
//     fonts.push("Hiragino Kaku Gothic Pro");
//     fonts.push("Hiragino Kaku Gothic ProN");
//     fonts.push("Hiragino Kaku Gothic Std");
//     fonts.push("Hiragino Kaku Gothic StdN");
//     fonts.push("Hiragino Maru Gothic Pro");
//     fonts.push("Hiragino Maru Gothic ProN");
//     fonts.push("Hiragino Mincho Pro");
//     fonts.push("Hiragino Mincho ProN");
//     fonts.push("Hoefler Text");
//     fonts.push("Inai Mathi");
//     fonts.push("Impact");
//     fonts.push("Jung Gothic");
//     fonts.push("Kai");
//     fonts.push("Keyboard");
//     fonts.push("Krungthep");
//     fonts.push("KufiStandard GK");
//     fonts.push("LastResort");
//     fonts.push("LiHei Pro");
//     fonts.push("LiSong Pro");
//     fonts.push("Lucida Grande");
//     fonts.push("Marker Felt");
//     fonts.push("Menlo");
//     fonts.push("Monaco");
//     fonts.push("Monaco CY");
//     fonts.push("Mshtakan");
//     fonts.push("Nadeem");
//     fonts.push("New Peninim");
//     fonts.push("New York");
//     fonts.push("NISC GB18030");
//     fonts.push("Optima");
//     fonts.push("Osaka");
//     fonts.push("Palatino");
//     fonts.push("Papyrus");
//     fonts.push("PC Myungjo");
//     fonts.push("Pilgiche");
//     fonts.push("Plantagenet Cherokee");
//     fonts.push("Raanana");
//     fonts.push("Sand");
//     fonts.push("Sathu");
//     fonts.push("Seoul");
//     fonts.push("Shin Myungjo Neue");
//     fonts.push("Silom");
//     fonts.push("Skia");
//     fonts.push("Song");
//     fonts.push("ST FangSong");
//     fonts.push("ST Heiti");
//     fonts.push("ST Kaiti");
//     fonts.push("ST Song");
//     fonts.push("Symbol");
//     fonts.push("Tae Graphic");
//     fonts.push("Tahoma");
//     fonts.push("Taipei");
//     fonts.push("Techno");
//     fonts.push("Textile");
//     fonts.push("Thonburi");
//     fonts.push("Times");
//     fonts.push("Times CY");
//     fonts.push("Times New Roman");
//     fonts.push("Trebuchet MS");
//     fonts.push("Verdana");
//     fonts.push("Zapf Chancery");
//     fonts.push("Zapf Dingbats");
//     fonts.push("Zapfinofonts");
//     // BEGIN Windows Fonts - http://en.wikipedia.org/wiki/List_of_Microsoft_Windows_fonts
//     fonts.push("Abadi MT Condensed Light");
//     fonts.push("Aharoni");
//     fonts.push("Aldhabi");
//     fonts.push("Andalus");
//     fonts.push("Angsana New");
//     fonts.push("AngsanaUPC");
//     fonts.push("Aparajita");
//     fonts.push("Arabic Typesetting");
//     fonts.push("Arial");
//     fonts.push("Arial Black");
//     fonts.push("Batang");
//     fonts.push("BatangChe");
//     fonts.push("Book Antiqua");
//     fonts.push("Browallia New");
//     fonts.push("BrowalliaUPC");
//     fonts.push("Calibri");
//     fonts.push("Calibri Light");
//     fonts.push("Calisto MT");
//     fonts.push("Cambria");
//     fonts.push("Cambria Math");
//     fonts.push("Candara");
//     fonts.push("Century Gothic");
//     fonts.push("Comic Sans MS");
//     fonts.push("Consolas");
//     fonts.push("Constantia");
//     fonts.push("Copperplate GothicBold");
//     fonts.push("Copperplate Gothic Light");
//     fonts.push("Corbel");
//     fonts.push("Cordia New");
//     fonts.push("CordiaUPC");
//     fonts.push("Courier New");
//     fonts.push("DaunPenh");
//     fonts.push("David");
//     fonts.push("DFKai-SB");
//     fonts.push("DilleniaUPC");
//     fonts.push("DokChampa");
//     fonts.push("Dotum");
//     fonts.push("DotumChe");
//     fonts.push("Ebrima");
//     fonts.push("Estrangelo Edessa");
//     fonts.push("EucrosiaUPC");
//     fonts.push("Euphemia");
//     fonts.push("FangSong");
//     fonts.push("Franklin Gothic Medium");
//     fonts.push("FrankRuehl");
//     fonts.push("FreesiaUPC");
//     fonts.push("Gabriola");
//     fonts.push("Gadugi");
//     fonts.push("Gautami");
//     fonts.push("Georgia");
//     fonts.push("Gisha");
//     fonts.push("Gulim");
//     fonts.push("GulimChe");
//     fonts.push("Gungsuh");
//     fonts.push("GungsuhChe");
//     fonts.push("Impact");
//     fonts.push("IrisUPC");
//     fonts.push("Iskoola Pota");
//     fonts.push("JasmineUPC");
//     fonts.push("KaiTi");
//     fonts.push("Kalinga");
//     fonts.push("Kartika");
//     fonts.push("Khmer UI");
//     fonts.push("KodchiangUPC");
//     fonts.push("Kokila");
//     fonts.push("Lao UI");
//     fonts.push("Latha");
//     fonts.push("Leelawadee");
//     fonts.push("Levenim MT");
//     fonts.push("LilyUPC");
//     fonts.push("Lucida Console");
//     fonts.push("Lucida Handwriting Italic");
//     fonts.push("Lucida Sans Unicode");
//     fonts.push("Malgun Gothic");
//     fonts.push("Mangal");
//     fonts.push("Marlett");
//     fonts.push("Meiryo");
//     fonts.push("Meiryo UI");
//     fonts.push("Microsoft Himalaya");
//     fonts.push("Microsoft JhengHei");
//     fonts.push("Microsoft JhengHei UI");
//     fonts.push("Microsoft New Tai Lue");
//     fonts.push("Microsoft PhagsPa");
//     fonts.push("Microsoft Sans Serif");
//     fonts.push("Microsoft Tai Le");
//     fonts.push("Microsoft Uighur");
//     fonts.push("Microsoft YaHei");
//     fonts.push("Microsoft YaHei UI");
//     fonts.push("Microsoft Yi Baiti");
//     fonts.push("MingLiU, PMingLiU");
//     fonts.push("MingLiU-ExtB, PMingLiU-ExtB");
//     fonts.push("MingLiU_HKSCS");
//     fonts.push("MingLiU_HKSCS-ExtB");
//     fonts.push("Miriam");
//     fonts.push("Mongolian Baiti");
//     fonts.push("MoolBoran");
//     fonts.push("MS Gothic, MS PGothic");
//     fonts.push("MS Mincho, MS PMincho");
//     fonts.push("MS UI Gothic");
//     fonts.push("MV Boli");
//     fonts.push("Myanmar Text");
//     fonts.push("Narkisim");
//     fonts.push("Nirmala UI");
//     fonts.push("News Gothic MT");
//     fonts.push("NSimSun");
//     fonts.push("Nyala");
//     fonts.push("Palatino Linotype");
//     fonts.push("Plantagenet Cherokee");
//     fonts.push("Raavi");
//     fonts.push("Rod");
//     fonts.push("Sakkal Majalla");
//     fonts.push("Segoe Print");
//     fonts.push("Segoe Script");
//     fonts.push("Segoe UI v5.00[3]");
//     fonts.push("Segoe UI v5.01[4]");
//     fonts.push("Segoe UI v5.27[5]");
//     fonts.push("Segoe UI Symbol");
//     fonts.push("Shonar Bangla");
//     fonts.push("Shruti");
//     fonts.push("SimHei");
//     fonts.push("SimKai");
//     fonts.push("Simplified Arabic");
//     fonts.push("SimSun");
//     fonts.push("SimSun-ExtB");
//     fonts.push("Sylfaen");
//     fonts.push("Symbol");
//     fonts.push("Tahoma");
//     fonts.push("Times New Roman");
//     fonts.push("Traditional Arabic");
//     fonts.push("Trebuchet MS");
//     fonts.push("Tunga");
//     fonts.push("Urdu Typesetting");
//     fonts.push("Utsaah");
//     fonts.push("Vani");
//     fonts.push("Verdana");
//     fonts.push("Vijaya");
//     fonts.push("Vrinda");
//     fonts.push("Webdings");
//     fonts.push("Westminster");
//     fonts.push("Wingdingsfonts.push");
//     // BEGIN Wikipedia List - http://en.wikipedia.org/wiki/List_of_typefaces
//     fonts.push("Adobe Jenson");
//     fonts.push("Adobe Text");
//     fonts.push("Albertus");
//     fonts.push("Aldus");
//     fonts.push("Alexandria");
//     fonts.push("Algerian");
//     fonts.push("American Typewriter");
//     fonts.push("Antiqua");
//     fonts.push("Arno");
//     fonts.push("Aster");
//     fonts.push("Aurora");
//     fonts.push("News 706");
//     fonts.push("Baskerville");
//     fonts.push("Bebas");
//     fonts.push("Bebas Neue");
//     fonts.push("Bell");
//     fonts.push("Bembo");
//     fonts.push("Bembo Schoolbook");
//     fonts.push("Berkeley Old Style");
//     fonts.push("Bernhard Modern");
//     fonts.push("Bodoni");
//     fonts.push("Bauer Bodoni");
//     fonts.push("Book Antiqua");
//     fonts.push("Bookman");
//     fonts.push("Bordeaux Roman");
//     fonts.push("Bulmer");
//     fonts.push("Caledonia");
//     fonts.push("Californian FB");
//     fonts.push("Calisto MT");
//     fonts.push("Cambria");
//     fonts.push("Capitals");
//     fonts.push("Cartier");
//     fonts.push("Caslon");
//     fonts.push("Wyld");
//     fonts.push("Caslon Antique");
//     fonts.push("Fifteenth Century");
//     fonts.push("Catull");
//     fonts.push("Centaur");
//     fonts.push("Century Old Style");
//     fonts.push("Century Schoolbook");
//     fonts.push("New Century Schoolbook");
//     fonts.push("Century Schoolbook Infant");
//     fonts.push("Chaparral");
//     fonts.push("Charis SIL");
//     fonts.push("Charter");
//     fonts.push("Cheltenham");
//     fonts.push("Clearface");
//     fonts.push("Cochin");
//     fonts.push("Colonna");
//     fonts.push("Computer Modern");
//     fonts.push("Concrete Roman");
//     fonts.push("Constantia");
//     fonts.push("Cooper Black");
//     fonts.push("Corona");
//     fonts.push("News 705");
//     fonts.push("DejaVu Serif");
//     fonts.push("Didot");
//     fonts.push("Droid Serif");
//     fonts.push("Ecotype");
//     fonts.push("Elephant");
//     fonts.push("Emerson");
//     fonts.push("Espy Serif");
//     fonts.push("Excelsior");
//     fonts.push("News 702");
//     fonts.push("Fairfield");
//     fonts.push("FF Scala");
//     fonts.push("Footlight");
//     fonts.push("FreeSerif");
//     fonts.push("Friz Quadrata");
//     fonts.push("Garamond");
//     fonts.push("Gentium");
//     fonts.push("Georgia");
//     fonts.push("Gloucester");
//     fonts.push("Goudy");
//     fonts.push("Goudy Old Style");
//     fonts.push("Goudy Pro Font");
//     fonts.push("Goudy Schoolbook");
//     fonts.push("Granjon");
//     fonts.push("Heather");
//     fonts.push("Hercules");
//     fonts.push("High Tower Text");
//     fonts.push("Hiroshige");
//     fonts.push("Hoefler Text");
//     fonts.push("Humana Serif");
//     fonts.push("Imprint");
//     fonts.push("Ionic No. 5");
//     fonts.push("News 701");
//     fonts.push("ITC Benguiat");
//     fonts.push("Janson");
//     fonts.push("Jenson");
//     fonts.push("Joanna");
//     fonts.push("Korinna");
//     fonts.push("Kursivschrift");
//     fonts.push("Legacy Serif");
//     fonts.push("Lexicon");
//     fonts.push("Liberation Serif");
//     fonts.push("Linux Libertine");
//     fonts.push("Literaturnaya");
//     fonts.push("Lucida Bright");
//     fonts.push("Melior");
//     fonts.push("Memphis");
//     fonts.push("Miller");
//     fonts.push("Minion");
//     fonts.push("Modern");
//     fonts.push("Mona Lisa");
//     fonts.push("Mrs Eaves");
//     fonts.push("MS Serif");
//     fonts.push("New York");
//     fonts.push("Nimbus Roman");
//     fonts.push("NPS Rawlinson Roadway");
//     fonts.push("OCR A Extended");
//     fonts.push("Palatino");
//     fonts.push("Book Antiqua");
//     fonts.push("Perpetua");
//     fonts.push("Plantin");
//     fonts.push("Plantin Schoolbook");
//     fonts.push("Playbill");
//     fonts.push("Poor Richard");
//     fonts.push("Renault");
//     fonts.push("Requiem");
//     fonts.push("Roman");
//     fonts.push("Rotis Serif");
//     fonts.push("Sabon");
//     fonts.push("Seagull");
//     fonts.push("Sistina");
//     fonts.push("Souvenir");
//     fonts.push("STIX");
//     fonts.push("Stone Informal");
//     fonts.push("Stone Serif");
//     fonts.push("Sylfaen");
//     fonts.push("Times New Roman");
//     fonts.push("Times");
//     fonts.push("Trajan");
//     fonts.push("Trinité");
//     fonts.push("Trump Mediaeval");
//     fonts.push("Utopia");
//     fonts.push("Vale Type");
//     fonts.push("Vera Serif");
//     fonts.push("Versailles");
//     fonts.push("Wanted");
//     fonts.push("Weiss");
//     fonts.push("Wide Latin");
//     fonts.push("Windsor");
//     fonts.push("XITSfonts");
//     fonts.push("Alexandria");
//     fonts.push("Apex");
//     fonts.push("Archer");
//     fonts.push("Athens");
//     fonts.push("Cholla Slab");
//     fonts.push("City");
//     fonts.push("Clarendon");
//     fonts.push("Concrete Roman");
//     fonts.push("Courier");
//     fonts.push("Egyptienne");
//     fonts.push("Guardian Egyptian");
//     fonts.push("Ionic No. 5");
//     fonts.push("Lexia");
//     fonts.push("Museo Slab");
//     fonts.push("Nilland");
//     fonts.push("Rockwell");
//     fonts.push("Skeleton Antique");
//     fonts.push("Tower");
//     fonts.push("Abadi");
//     fonts.push("Agency FB");
//     fonts.push("Akzidenz-Grotesk");
//     fonts.push("Andalé Sans");
//     fonts.push("Aptifer");
//     fonts.push("Arial");
//     fonts.push("Arial Unicode MS");
//     fonts.push("Avant Garde Gothic");
//     fonts.push("Avenir");
//     fonts.push("Bank Gothic");
//     fonts.push("Barmeno");
//     fonts.push("Bauhaus");
//     fonts.push("Bell Centennial");
//     fonts.push("Bell Gothic");
//     fonts.push("Benguiat Gothic");
//     fonts.push("Berlin Sans");
//     fonts.push("Beteckna");
//     fonts.push("Blue Highway");
//     fonts.push("Brandon Grotesque");
//     fonts.push("Cabin");
//     fonts.push("Cafeteria");
//     fonts.push("Calibri");
//     fonts.push("Casey");
//     fonts.push("Century Gothic");
//     fonts.push("Charcoal");
//     fonts.push("Chicago");
//     fonts.push("Clearface Gothic");
//     fonts.push("Clearview");
//     fonts.push("Co Headline");
//     fonts.push("Co Text");
//     fonts.push("Compacta");
//     fonts.push("Corbel");
//     fonts.push("DejaVu Sans");
//     fonts.push("Dotum");
//     fonts.push("Droid Sans");
//     fonts.push("Dyslexie");
//     fonts.push("Ecofont");
//     fonts.push("Eras");
//     fonts.push("Espy Sans");
//     fonts.push("Nu Sans[1]");
//     fonts.push("Eurocrat");
//     fonts.push("Eurostile");
//     fonts.push("Square 721");
//     fonts.push("FF Dax");
//     fonts.push("FF Meta");
//     fonts.push("FF Scala Sans");
//     fonts.push("Flama");
//     fonts.push("Formata");
//     fonts.push("Franklin Gothic");
//     fonts.push("FreeSans");
//     fonts.push("Frutiger");
//     fonts.push("Frutiger Next");
//     fonts.push("Futura");
//     fonts.push("Geneva");
//     fonts.push("Gill Sans");
//     fonts.push("Gill Sans Schoolbook");
//     fonts.push("Gotham");
//     fonts.push("Haettenschweiler");
//     fonts.push("Handel Gothic");
//     fonts.push("Denmark");
//     fonts.push("Hei");
//     fonts.push("Helvetica");
//     fonts.push("Helvetica Neue");
//     fonts.push("Swiss 721");
//     fonts.push("Highway Gothic");
//     fonts.push("Hiroshige Sans");
//     fonts.push("Hobo");
//     fonts.push("Impact");
//     fonts.push("Industria");
//     fonts.push("Interstate");
//     fonts.push("Johnston/New Johnston");
//     fonts.push("Kabel");
//     fonts.push("Lato");
//     fonts.push("ITC Legacy Sans");
//     fonts.push("Lexia Readable");
//     fonts.push("Liberation Sans");
//     fonts.push("Lucida Sans");
//     fonts.push("Meiryo");
//     fonts.push("Microgramma");
//     fonts.push("Modern");
//     fonts.push("Motorway");
//     fonts.push("MS Sans Serif");
//     fonts.push("Museo Sans");
//     fonts.push("Myriad");
//     fonts.push("Neutraface");
//     fonts.push("Neuzeit S");
//     fonts.push("News Gothic");
//     fonts.push("Nimbus Sans L");
//     fonts.push("Nina");
//     fonts.push("Open Sans");
//     fonts.push("Optima");
//     fonts.push("Parisine");
//     fonts.push("Pricedown");
//     fonts.push("Prima Sans");
//     fonts.push("PT Sans");
//     fonts.push("Rail Alphabet");
//     fonts.push("Revue");
//     fonts.push("Roboto");
//     fonts.push("Rotis Sans");
//     fonts.push("Segoe UI");
//     fonts.push("Skia");
//     fonts.push("Souvenir Gothic");
//     fonts.push("ITC Stone Sans");
//     fonts.push("Syntax");
//     fonts.push("Tahoma");
//     fonts.push("Template Gothic");
//     fonts.push("Thesis Sans");
//     fonts.push("Tiresias");
//     fonts.push("Trade Gothic");
//     fonts.push("Transport");
//     fonts.push("Trebuchet MS");
//     fonts.push("Trump Gothic");
//     fonts.push("Twentieth Century");
//     fonts.push("Ubuntu");
//     fonts.push("Univers");
//     fonts.push("Zurich");
//     fonts.push("Vera Sans");
//     fonts.push("Verdana");
//     fonts.push("Virtue");
//     fonts.push("Amsterdam Old Style");
//     fonts.push("Divona");
//     fonts.push("Nyala");
//     fonts.push("Portobello");
//     fonts.push("Rotis Semi Serif");
//     fonts.push("Tema Cantante");
//     fonts.push("Andale Mono");
//     fonts.push("Anonymous and Anonymous Pro");
//     fonts.push("Arial Monospaced");
//     fonts.push("Bitstream Vera");
//     fonts.push("Consolas");
//     fonts.push("Courier");
//     fonts.push("CourierHP");
//     fonts.push("Courier New");
//     fonts.push("CourierPS");
//     fonts.push("Fontcraft Courier");
//     fonts.push("DejaVu Sans Mono");
//     fonts.push("Droid Sans Mono");
//     fonts.push("Everson Mono");
//     fonts.push("Fedra Mono");
//     fonts.push("Fixed");
//     fonts.push("Fixedsys");
//     fonts.push("Fixedsys Excelsior");
//     fonts.push("HyperFont");
//     fonts.push("Inconsolata");
//     fonts.push("Letter Gothic");
//     fonts.push("Liberation Mono");
//     fonts.push("Lucida Console");
//     fonts.push("Lucida Sans Typewriter");
//     fonts.push("Lucida Typewriter");
//     fonts.push("Menlo");
//     fonts.push("MICR");
//     fonts.push("Miriam Fixed");
//     fonts.push("Monaco");
//     fonts.push("Monofur");
//     fonts.push("Monospace");
//     fonts.push("MS Gothic");
//     fonts.push("MS Mincho");
//     fonts.push("Nimbus Mono L");
//     fonts.push("OCR-A");
//     fonts.push("OCR-B");
//     fonts.push("Orator");
//     fonts.push("Ormaxx");
//     fonts.push("PragmataPro");
//     fonts.push("Prestige Elite");
//     fonts.push("ProFont");
//     fonts.push("Proggy programming fonts");
//     fonts.push("Small Fonts");
//     fonts.push("Sydnie");
//     fonts.push("Terminal");
//     fonts.push("Tex Gyre Cursor");
//     fonts.push("Trixie");
//     fonts.push("Ubuntu Mono");
//     fonts.push("UM Typewriter");
//     fonts.push("Vera Sans Mono");
//     fonts.push("William Monospace");
//     fonts.push("Balloon");
//     fonts.push("Brush Script");
//     fonts.push("Choc");
//     fonts.push("Dom Casual");
//     fonts.push("Dragonwick");
//     fonts.push("Mistral");
//     fonts.push("Papyrus");
//     fonts.push("Segoe Script");
//     fonts.push("Tempus Sans");
//     fonts.push("Utopia");
//     fonts.push("Amazone");
//     fonts.push("American Scribe");
//     fonts.push("AMS Euler");
//     fonts.push("Apple Chancery");
//     fonts.push("Aquiline");
//     fonts.push("Aristocrat");
//     fonts.push("Bickley Script");
//     fonts.push("Civitype");
//     fonts.push("Codex");
//     fonts.push("Edwardian Script");
//     fonts.push("Forte");
//     fonts.push("French Script");
//     fonts.push("ITC Zapf Chancery");
//     fonts.push("Kuenstler Script");
//     fonts.push("Monotype Corsiva");
//     fonts.push("Old English Text MT");
//     fonts.push("Palace Script");
//     fonts.push("Park Avenue");
//     fonts.push("Scriptina");
//     fonts.push("Shelley Volante");
//     fonts.push("Vivaldi");
//     fonts.push("Vladimir Script");
//     fonts.push("Zapfino");
//     fonts.push("Andy");
//     fonts.push("Ashley Script");
//     fonts.push("Cézanne");
//     fonts.push("Chalkboard");
//     fonts.push("Comic Sans MS");
//     fonts.push("Dom Casual");
//     fonts.push("Fontoon");
//     fonts.push("Irregularis");
//     fonts.push("Jefferson");
//     fonts.push("Kristen");
//     fonts.push("Lucida Handwriting");
//     fonts.push("Rage Italic");
//     fonts.push("Rufscript");
//     fonts.push("Scribble");
//     fonts.push("Soupbone");
//     fonts.push("Tekton");
//     fonts.push("Alecko");
//     fonts.push("Cinderella");
//     fonts.push("Coronet");
//     fonts.push("Cupola");
//     fonts.push("Curlz");
//     fonts.push("Magnificat");
//     fonts.push("Script");
//     fonts.push("Stone Informal");
//     fonts.push("American Text");
//     fonts.push("Bastard");
//     fonts.push("Breitkopf Fraktur");
//     fonts.push("Cloister Black");
//     fonts.push("Fette Fraktur");
//     fonts.push("Fletcher");
//     fonts.push("Fraktur");
//     fonts.push("Goudy Text");
//     fonts.push("Lucida Blackletter");
//     fonts.push("Old English Text");
//     fonts.push("Schwabacher");
//     fonts.push("Wedding Text");
//     fonts.push("Aegyptus");
//     fonts.push("Aharoni");
//     fonts.push("Aisha");
//     fonts.push("Amienne");
//     fonts.push("Batak Script");
//     fonts.push("Chandas");
//     fonts.push("Grecs du roi");
//     fonts.push("Hanacaraka");
//     fonts.push("Japanese Gothic");
//     fonts.push("Jomolhari");
//     fonts.push("Kochi");
//     fonts.push("Koren");
//     fonts.push("Lontara Script");
//     fonts.push("Maiola");
//     fonts.push("Malgun Gothic");
//     fonts.push("Meiryo");
//     fonts.push("Microsoft JhengHei");
//     fonts.push("Microsoft YaHei");
//     fonts.push("Minchō");
//     fonts.push("Ming");
//     fonts.push("Mona");
//     fonts.push("MS Gothic");
//     fonts.push("Nassim");
//     fonts.push("Nastaliq Navees");
//     fonts.push("Neacademia");
//     fonts.push("Perpetua Greek[2]");
//     fonts.push("Porson");
//     fonts.push("SimSun");
//     fonts.push("Skolar");
//     fonts.push("Skolar Devanagari");
//     fonts.push("Sundanese Unicode");
//     fonts.push("Sutturah");
//     fonts.push("Sylfaen");
//     fonts.push("Tai Le Valentinium");
//     fonts.push("Tengwar");
//     fonts.push("Tibetan Machine Uni");
//     fonts.push("Tunga");
//     fonts.push("Wadalab");
//     fonts.push("Wilson Greek");
//     fonts.push("Apple Symbols");
//     fonts.push("Asana-Math");
//     fonts.push("Blackboard bold");
//     fonts.push("Bookshelf Symbol 7");
//     fonts.push("Braille");
//     fonts.push("Cambria Math");
//     fonts.push("Commercial Pi");
//     fonts.push("Computer Modern");
//     fonts.push("Corel");
//     fonts.push("Erler Dingbats");
//     fonts.push("HM Phonetic");
//     fonts.push("Lucida Math");
//     fonts.push("Marlett");
//     fonts.push("Mathematical Pi");
//     fonts.push("Morse Code");
//     fonts.push("OpenSymbol");
//     fonts.push("RichStyle");
//     fonts.push("Symbol");
//     fonts.push("SymbolPS");
//     fonts.push("Webdings");
//     fonts.push("Wingdings");
//     fonts.push("Wingdings 2");
//     fonts.push("Wingdings 3");
//     fonts.push("Zapf Dingbats");
//     fonts.push("Abracadabra");
//     fonts.push("Ad Lib");
//     fonts.push("Allegro");
//     fonts.push("Andreas");
//     fonts.push("Arnold Böcklin");
//     fonts.push("Astur");
//     fonts.push("Balloon Pop Outlaw Black");
//     fonts.push("Banco");
//     fonts.push("Bauhaus");
//     fonts.push("Beat");
//     fonts.push("Braggadocio");
//     fonts.push("Broadway");
//     fonts.push("Caslon Antique");
//     fonts.push("Cooper Black");
//     fonts.push("Curlz");
//     fonts.push("Ellington");
//     fonts.push("Exablock");
//     fonts.push("Exocet");
//     fonts.push("FIG Script");
//     fonts.push("Forte");
//     fonts.push("Gabriola");
//     fonts.push("Gigi");
//     fonts.push("Harlow Solid");
//     fonts.push("Harrington");
//     fonts.push("Horizon");
//     fonts.push("Jim Crow");
//     fonts.push("Jokerman");
//     fonts.push("Juice");
//     fonts.push("Lo-Type");
//     fonts.push("Magneto");
//     fonts.push("Megadeth");
//     fonts.push("Neuland");
//     fonts.push("Peignot");
//     fonts.push("Ravie");
//     fonts.push("San Francisco");
//     fonts.push("Showcard Gothic");
//     fonts.push("Snap");
//     fonts.push("Stencil");
//     fonts.push("Umbra");
//     fonts.push("Westminster");
//     fonts.push("Willow");
//     fonts.push("Windsor");
//     // BEGIN Google Fonts - http://worknotes.scripting.com/february2012/22612ByDw/listOfGoogleFonts
//     fonts.push("ABeeZee");
//     fonts.push("Abel");
//     fonts.push("Abril Fatface");
//     fonts.push("Aclonica");
//     fonts.push("Acme");
//     fonts.push("Actor");
//     fonts.push("Adamina");
//     fonts.push("Advent Pro");
//     fonts.push("Aguafina Script");
//     fonts.push("Akronim");
//     fonts.push("Aladin");
//     fonts.push("Aldrich");
//     fonts.push("Alef");
//     fonts.push("Alegreya");
//     fonts.push("Alegreya Sans");
//     fonts.push("Alegreya Sans SC");
//     fonts.push("Alegreya SC");
//     fonts.push("Alex Brush");
//     fonts.push("Alfa Slab One");
//     fonts.push("Alice");
//     fonts.push("Alike");
//     fonts.push("Alike Angular");
//     fonts.push("Allan");
//     fonts.push("Allerta");
//     fonts.push("Allerta Stencil");
//     fonts.push("Allura");
//     fonts.push("Almendra");
//     fonts.push("Almendra Display");
//     fonts.push("Almendra SC");
//     fonts.push("Amarante");
//     fonts.push("Amaranth");
//     fonts.push("Amatic SC");
//     fonts.push("Amethysta");
//     fonts.push("Anaheim");
//     fonts.push("Andada");
//     fonts.push("Andika");
//     fonts.push("Angkor");
//     fonts.push("Annie Use Your Telescope");
//     fonts.push("Anonymous Pro");
//     fonts.push("Antic");
//     fonts.push("Antic Didone");
//     fonts.push("Antic Slab");
//     fonts.push("Anton");
//     fonts.push("Arapey");
//     fonts.push("Arbutus");
//     fonts.push("Arbutus Slab");
//     fonts.push("Architects Daughter");
//     fonts.push("Archivo Black");
//     fonts.push("Archivo Narrow");
//     fonts.push("Arimo");
//     fonts.push("Arizonia");
//     fonts.push("Armata");
//     fonts.push("Artifika");
//     fonts.push("Arvo");
//     fonts.push("Asap");
//     fonts.push("Asset");
//     fonts.push("Astloch");
//     fonts.push("Asul");
//     fonts.push("Atomic Age");
//     fonts.push("Aubrey");
//     fonts.push("Audiowide");
//     fonts.push("Autour One");
//     fonts.push("Average");
//     fonts.push("Average Sans");
//     fonts.push("Averia Gruesa Libre");
//     fonts.push("Averia Libre");
//     fonts.push("Averia Sans Libre");
//     fonts.push("Averia Serif Libre");
//     fonts.push("Bad Script");
//     fonts.push("Balthazar");
//     fonts.push("Bangers");
//     fonts.push("Basic");
//     fonts.push("Battambang");
//     fonts.push("Baumans");
//     fonts.push("Bayon");
//     fonts.push("Belgrano");
//     fonts.push("Belleza");
//     fonts.push("BenchNine");
//     fonts.push("Bentham");
//     fonts.push("Berkshire Swash");
//     fonts.push("Bevan");
//     fonts.push("Bigelow Rules");
//     fonts.push("Bigshot One");
//     fonts.push("Bilbo");
//     fonts.push("Bilbo Swash Caps");
//     fonts.push("Bitter");
//     fonts.push("Black Ops One");
//     fonts.push("Bokor");
//     fonts.push("Bonbon");
//     fonts.push("Boogaloo");
//     fonts.push("Bowlby One");
//     fonts.push("Bowlby One SC");
//     fonts.push("Brawler");
//     fonts.push("Bree Serif");
//     fonts.push("Bubblegum Sans");
//     fonts.push("Bubbler One");
//     fonts.push("Buda");
//     fonts.push("Buenard");
//     fonts.push("Butcherman");
//     fonts.push("Butterfly Kids");
//     fonts.push("Cabin");
//     fonts.push("Cabin Condensed");
//     fonts.push("Cabin Sketch");
//     fonts.push("Caesar Dressing");
//     fonts.push("Cagliostro");
//     fonts.push("Calligraffitti");
//     fonts.push("Cambo");
//     fonts.push("Candal");
//     fonts.push("Cantarell");
//     fonts.push("Cantata One");
//     fonts.push("Cantora One");
//     fonts.push("Capriola");
//     fonts.push("Cardo");
//     fonts.push("Carme");
//     fonts.push("Carrois Gothic");
//     fonts.push("Carrois Gothic SC");
//     fonts.push("Carter One");
//     fonts.push("Caudex");
//     fonts.push("Cedarville Cursive");
//     fonts.push("Ceviche One");
//     fonts.push("Changa One");
//     fonts.push("Chango");
//     fonts.push("Chau Philomene One");
//     fonts.push("Chela One");
//     fonts.push("Chelsea Market");
//     fonts.push("Chenla");
//     fonts.push("Cherry Cream Soda");
//     fonts.push("Cherry Swash");
//     fonts.push("Chewy");
//     fonts.push("Chicle");
//     fonts.push("Chivo");
//     fonts.push("Cinzel");
//     fonts.push("Cinzel Decorative");
//     fonts.push("Clicker Script");
//     fonts.push("Coda");
//     fonts.push("Coda Caption");
//     fonts.push("Codystar");
//     fonts.push("Combo");
//     fonts.push("Comfortaa");
//     fonts.push("Coming Soon");
//     fonts.push("Concert One");
//     fonts.push("Condiment");
//     fonts.push("Content");
//     fonts.push("Contrail One");
//     fonts.push("Convergence");
//     fonts.push("Cookie");
//     fonts.push("Copse");
//     fonts.push("Corben");
//     fonts.push("Courgette");
//     fonts.push("Cousine");
//     fonts.push("Coustard");
//     fonts.push("Covered By Your Grace");
//     fonts.push("Crafty Girls");
//     fonts.push("Creepster");
//     fonts.push("Crete Round");
//     fonts.push("Crimson Text");
//     fonts.push("Croissant One");
//     fonts.push("Crushed");
//     fonts.push("Cuprum");
//     fonts.push("Cutive");
//     fonts.push("Cutive Mono");
//     fonts.push("Damion");
//     fonts.push("Dancing Script");
//     fonts.push("Dangrek");
//     fonts.push("Dawning of a New Day");
//     fonts.push("Days One");
//     fonts.push("Delius");
//     fonts.push("Delius Swash Caps");
//     fonts.push("Delius Unicase");
//     fonts.push("Della Respira");
//     fonts.push("Denk One");
//     fonts.push("Devonshire");
//     fonts.push("Didact Gothic");
//     fonts.push("Diplomata");
//     fonts.push("Diplomata SC");
//     fonts.push("Domine");
//     fonts.push("Donegal One");
//     fonts.push("Doppio One");
//     fonts.push("Dorsa");
//     fonts.push("Dosis");
//     fonts.push("Dr Sugiyama");
//     fonts.push("Droid Sans");
//     fonts.push("Droid Sans Mono");
//     fonts.push("Droid Serif");
//     fonts.push("Duru Sans");
//     fonts.push("Dynalight");
//     fonts.push("Eagle Lake");
//     fonts.push("Eater");
//     fonts.push("EB Garamond");
//     fonts.push("Economica");
//     fonts.push("Ek Mukta");
//     fonts.push("Electrolize");
//     fonts.push("Elsie");
//     fonts.push("Elsie Swash Caps");
//     fonts.push("Emblema One");
//     fonts.push("Emilys Candy");
//     fonts.push("Engagement");
//     fonts.push("Englebert");
//     fonts.push("Enriqueta");
//     fonts.push("Erica One");
//     fonts.push("Esteban");
//     fonts.push("Euphoria Script");
//     fonts.push("Ewert");
//     fonts.push("Exo");
//     fonts.push("Exo 2");
//     fonts.push("Expletus Sans");
//     fonts.push("Fanwood Text");
//     fonts.push("Fascinate");
//     fonts.push("Fascinate Inline");
//     fonts.push("Faster One");
//     fonts.push("Fasthand");
//     fonts.push("Fauna One");
//     fonts.push("Federant");
//     fonts.push("Federo");
//     fonts.push("Felipa");
//     fonts.push("Fenix");
//     fonts.push("Finger Paint");
//     fonts.push("Fira Mono");
//     fonts.push("Fira Sans");
//     fonts.push("Fjalla One");
//     fonts.push("Fjord One");
//     fonts.push("Flamenco");
//     fonts.push("Flavors");
//     fonts.push("Fondamento");
//     fonts.push("Fontdiner Swanky");
//     fonts.push("Forum");
//     fonts.push("Francois One");
//     fonts.push("Freckle Face");
//     fonts.push("Fredericka the Great");
//     fonts.push("Fredoka One");
//     fonts.push("Freehand");
//     fonts.push("Fresca");
//     fonts.push("Frijole");
//     fonts.push("Fruktur");
//     fonts.push("Fugaz One");
//     fonts.push("Gabriela");
//     fonts.push("Gafata");
//     fonts.push("Galdeano");
//     fonts.push("Galindo");
//     fonts.push("Gentium Basic");
//     fonts.push("Gentium Book Basic");
//     fonts.push("Geo");
//     fonts.push("Geostar");
//     fonts.push("Geostar Fill");
//     fonts.push("Germania One");
//     fonts.push("GFS Didot");
//     fonts.push("GFS Neohellenic");
//     fonts.push("Gilda Display");
//     fonts.push("Give You Glory");
//     fonts.push("Glass Antiqua");
//     fonts.push("Glegoo");
//     fonts.push("Gloria Hallelujah");
//     fonts.push("Goblin One");
//     fonts.push("Gochi Hand");
//     fonts.push("Gorditas");
//     fonts.push("Goudy Bookletter 1911");
//     fonts.push("Graduate");
//     fonts.push("Grand Hotel");
//     fonts.push("Gravitas One");
//     fonts.push("Great Vibes");
//     fonts.push("Griffy");
//     fonts.push("Gruppo");
//     fonts.push("Gudea");
//     fonts.push("Habibi");
//     fonts.push("Hammersmith One");
//     fonts.push("Hanalei");
//     fonts.push("Hanalei Fill");
//     fonts.push("Handlee");
//     fonts.push("Hanuman");
//     fonts.push("Happy Monkey");
//     fonts.push("Headland One");
//     fonts.push("Henny Penny");
//     fonts.push("Herr Von Muellerhoff");
//     fonts.push("Hind");
//     fonts.push("Holtwood One SC");
//     fonts.push("Homemade Apple");
//     fonts.push("Homenaje");
//     fonts.push("Iceberg");
//     fonts.push("Iceland");
//     fonts.push("IM Fell Double Pica");
//     fonts.push("IM Fell Double Pica SC");
//     fonts.push("IM Fell DW Pica");
//     fonts.push("IM Fell DW Pica SC");
//     fonts.push("IM Fell English");
//     fonts.push("IM Fell English SC");
//     fonts.push("IM Fell French Canon");
//     fonts.push("IM Fell French Canon SC");
//     fonts.push("IM Fell Great Primer");
//     fonts.push("IM Fell Great Primer SC");
//     fonts.push("Imprima");
//     fonts.push("Inconsolata");
//     fonts.push("Inder");
//     fonts.push("Indie Flower");
//     fonts.push("Inika");
//     fonts.push("Irish Grover");
//     fonts.push("Istok Web");
//     fonts.push("Italiana");
//     fonts.push("Italianno");
//     fonts.push("Jacques Francois");
//     fonts.push("Jacques Francois Shadow");
//     fonts.push("Jim Nightshade");
//     fonts.push("Jockey One");
//     fonts.push("Jolly Lodger");
//     fonts.push("Josefin Sans");
//     fonts.push("Josefin Slab");
//     fonts.push("Joti One");
//     fonts.push("Judson");
//     fonts.push("Julee");
//     fonts.push("Julius Sans One");
//     fonts.push("Junge");
//     fonts.push("Jura");
//     fonts.push("Just Another Hand");
//     fonts.push("Just Me Again Down Here");
//     fonts.push("Kalam");
//     fonts.push("Kameron");
//     fonts.push("Kantumruy");
//     fonts.push("Karla");
//     fonts.push("Karma");
//     fonts.push("Kaushan Script");
//     fonts.push("Kavoon");
//     fonts.push("Kdam Thmor");
//     fonts.push("Keania One");
//     fonts.push("Kelly Slab");
//     fonts.push("Kenia");
//     fonts.push("Khmer");
//     fonts.push("Kite One");
//     fonts.push("Knewave");
//     fonts.push("Kotta One");
//     fonts.push("Koulen");
//     fonts.push("Kranky");
//     fonts.push("Kreon");
//     fonts.push("Kristi");
//     fonts.push("Krona One");
//     fonts.push("La Belle Aurore");
//     fonts.push("Lancelot");
//     fonts.push("Lato");
//     fonts.push("League Script");
//     fonts.push("Leckerli One");
//     fonts.push("Ledger");
//     fonts.push("Lekton");
//     fonts.push("Lemon");
//     fonts.push("Libre Baskerville");
//     fonts.push("Life Savers");
//     fonts.push("Lilita One");
//     fonts.push("Lily Script One");
//     fonts.push("Limelight");
//     fonts.push("Linden Hill");
//     fonts.push("Lobster");
//     fonts.push("Lobster Two");
//     fonts.push("Londrina Outline");
//     fonts.push("Londrina Shadow");
//     fonts.push("Londrina Sketch");
//     fonts.push("Londrina Solid");
//     fonts.push("Lora");
//     fonts.push("Love Ya Like A Sister");
//     fonts.push("Loved by the King");
//     fonts.push("Lovers Quarrel");
//     fonts.push("Luckiest Guy");
//     fonts.push("Lusitana");
//     fonts.push("Lustria");
//     fonts.push("Macondo");
//     fonts.push("Macondo Swash Caps");
//     fonts.push("Magra");
//     fonts.push("Maiden Orange");
//     fonts.push("Mako");
//     fonts.push("Marcellus");
//     fonts.push("Marcellus SC");
//     fonts.push("Marck Script");
//     fonts.push("Margarine");
//     fonts.push("Marko One");
//     fonts.push("Marmelad");
//     fonts.push("Marvel");
//     fonts.push("Mate");
//     fonts.push("Mate SC");
//     fonts.push("Maven Pro");
//     fonts.push("McLaren");
//     fonts.push("Meddon");
//     fonts.push("MedievalSharp");
//     fonts.push("Medula One");
//     fonts.push("Megrim");
//     fonts.push("Meie Script");
//     fonts.push("Merienda");
//     fonts.push("Merienda One");
//     fonts.push("Merriweather");
//     fonts.push("Merriweather Sans");
//     fonts.push("Metal");
//     fonts.push("Metal Mania");
//     fonts.push("Metamorphous");
//     fonts.push("Metrophobic");
//     fonts.push("Michroma");
//     fonts.push("Milonga");
//     fonts.push("Miltonian");
//     fonts.push("Miltonian Tattoo");
//     fonts.push("Miniver");
//     fonts.push("Miss Fajardose");
//     fonts.push("Modern Antiqua");
//     fonts.push("Molengo");
//     fonts.push("Molle");
//     fonts.push("Monda");
//     fonts.push("Monofett");
//     fonts.push("Monoton");
//     fonts.push("Monsieur La Doulaise");
//     fonts.push("Montaga");
//     fonts.push("Montez");
//     fonts.push("Montserrat");
//     fonts.push("Montserrat Alternates");
//     fonts.push("Montserrat Subrayada");
//     fonts.push("Moul");
//     fonts.push("Moulpali");
//     fonts.push("Mountains of Christmas");
//     fonts.push("Mouse Memoirs");
//     fonts.push("Mr Bedfort");
//     fonts.push("Mr Dafoe");
//     fonts.push("Mr De Haviland");
//     fonts.push("Mrs Saint Delafield");
//     fonts.push("Mrs Sheppards");
//     fonts.push("Muli");
//     fonts.push("Mystery Quest");
//     fonts.push("Neucha");
//     fonts.push("Neuton");
//     fonts.push("New Rocker");
//     fonts.push("News Cycle");
//     fonts.push("Niconne");
//     fonts.push("Nixie One");
//     fonts.push("Nobile");
//     fonts.push("Nokora");
//     fonts.push("Norican");
//     fonts.push("Nosifer");
//     fonts.push("Nothing You Could Do");
//     fonts.push("Noticia Text");
//     fonts.push("Noto Sans");
//     fonts.push("Noto Serif");
//     fonts.push("Nova Cut");
//     fonts.push("Nova Flat");
//     fonts.push("Nova Mono");
//     fonts.push("Nova Oval");
//     fonts.push("Nova Round");
//     fonts.push("Nova Script");
//     fonts.push("Nova Slim");
//     fonts.push("Nova Square");
//     fonts.push("Numans");
//     fonts.push("Nunito");
//     fonts.push("Odor Mean Chey");
//     fonts.push("Offside");
//     fonts.push("Old Standard TT");
//     fonts.push("Oldenburg");
//     fonts.push("Oleo Script");
//     fonts.push("Oleo Script Swash Caps");
//     fonts.push("Open Sans");
//     fonts.push("Open Sans Condensed");
//     fonts.push("Oranienbaum");
//     fonts.push("Orbitron");
//     fonts.push("Oregano");
//     fonts.push("Orienta");
//     fonts.push("Original Surfer");
//     fonts.push("Oswald");
//     fonts.push("Over the Rainbow");
//     fonts.push("Overlock");
//     fonts.push("Overlock SC");
//     fonts.push("Ovo");
//     fonts.push("Oxygen");
//     fonts.push("Oxygen Mono");
//     fonts.push("Pacifico");
//     fonts.push("Paprika");
//     fonts.push("Parisienne");
//     fonts.push("Passero One");
//     fonts.push("Passion One");
//     fonts.push("Pathway Gothic One");
//     fonts.push("Patrick Hand");
//     fonts.push("Patrick Hand SC");
//     fonts.push("Patua One");
//     fonts.push("Paytone One");
//     fonts.push("Peralta");
//     fonts.push("Permanent Marker");
//     fonts.push("Petit Formal Script");
//     fonts.push("Petrona");
//     fonts.push("Philosopher");
//     fonts.push("Piedra");
//     fonts.push("Pinyon Script");
//     fonts.push("Pirata One");
//     fonts.push("Plaster");
//     fonts.push("Play");
//     fonts.push("Playball");
//     fonts.push("Playfair Display");
//     fonts.push("Playfair Display SC");
//     fonts.push("Podkova");
//     fonts.push("Poiret One");
//     fonts.push("Poller One");
//     fonts.push("Poly");
//     fonts.push("Pompiere");
//     fonts.push("Pontano Sans");
//     fonts.push("Port Lligat Sans");
//     fonts.push("Port Lligat Slab");
//     fonts.push("Prata");
//     fonts.push("Preahvihear");
//     fonts.push("Press Start 2P");
//     fonts.push("Princess Sofia");
//     fonts.push("Prociono");
//     fonts.push("Prosto One");
//     fonts.push("PT Mono");
//     fonts.push("PT Sans");
//     fonts.push("PT Sans Caption");
//     fonts.push("PT Sans Narrow");
//     fonts.push("PT Serif");
//     fonts.push("PT Serif Caption");
//     fonts.push("Puritan");
//     fonts.push("Purple Purse");
//     fonts.push("Quando");
//     fonts.push("Quantico");
//     fonts.push("Quattrocento");
//     fonts.push("Quattrocento Sans");
//     fonts.push("Questrial");
//     fonts.push("Quicksand");
//     fonts.push("Quintessential");
//     fonts.push("Qwigley");
//     fonts.push("Racing Sans One");
//     fonts.push("Radley");
//     fonts.push("Rajdhani");
//     fonts.push("Raleway");
//     fonts.push("Raleway Dots");
//     fonts.push("Rambla");
//     fonts.push("Rammetto One");
//     fonts.push("Ranchers");
//     fonts.push("Rancho");
//     fonts.push("Rationale");
//     fonts.push("Redressed");
//     fonts.push("Reenie Beanie");
//     fonts.push("Revalia");
//     fonts.push("Ribeye");
//     fonts.push("Ribeye Marrow");
//     fonts.push("Righteous");
//     fonts.push("Risque");
//     fonts.push("Roboto");
//     fonts.push("Roboto Condensed");
//     fonts.push("Roboto Slab");
//     fonts.push("Rochester");
//     fonts.push("Rock Salt");
//     fonts.push("Rokkitt");
//     fonts.push("Romanesco");
//     fonts.push("Ropa Sans");
//     fonts.push("Rosario");
//     fonts.push("Rosarivo");
//     fonts.push("Rouge Script");
//     fonts.push("Rubik Mono One");
//     fonts.push("Rubik One");
//     fonts.push("Ruda");
//     fonts.push("Rufina");
//     fonts.push("Ruge Boogie");
//     fonts.push("Ruluko");
//     fonts.push("Rum Raisin");
//     fonts.push("Ruslan Display");
//     fonts.push("Russo One");
//     fonts.push("Ruthie");
//     fonts.push("Rye");
//     fonts.push("Sacramento");
//     fonts.push("Sail");
//     fonts.push("Salsa");
//     fonts.push("Sanchez");
//     fonts.push("Sancreek");
//     fonts.push("Sansita One");
//     fonts.push("Sarina");
//     fonts.push("Satisfy");
//     fonts.push("Scada");
//     fonts.push("Schoolbell");
//     fonts.push("Seaweed Script");
//     fonts.push("Sevillana");
//     fonts.push("Seymour One");
//     fonts.push("Shadows Into Light");
//     fonts.push("Shadows Into Light Two");
//     fonts.push("Shanti");
//     fonts.push("Share");
//     fonts.push("Share Tech");
//     fonts.push("Share Tech Mono");
//     fonts.push("Shojumaru");
//     fonts.push("Short Stack");
//     fonts.push("Siemreap");
//     fonts.push("Sigmar One");
//     fonts.push("Signika");
//     fonts.push("Signika Negative");
//     fonts.push("Simonetta");
//     fonts.push("Sintony");
//     fonts.push("Sirin Stencil");
//     fonts.push("Six Caps");
//     fonts.push("Skranji");
//     fonts.push("Slackey");
//     fonts.push("Smokum");
//     fonts.push("Smythe");
//     fonts.push("Sniglet");
//     fonts.push("Snippet");
//     fonts.push("Snowburst One");
//     fonts.push("Sofadi One");
//     fonts.push("Sofia");
//     fonts.push("Sonsie One");
//     fonts.push("Sorts Mill Goudy");
//     fonts.push("Source Code Pro");
//     fonts.push("Source Sans Pro");
//     fonts.push("Source Serif Pro");
//     fonts.push("Special Elite");
//     fonts.push("Spicy Rice");
//     fonts.push("Spinnaker");
//     fonts.push("Spirax");
//     fonts.push("Squada One");
//     fonts.push("Stalemate");
//     fonts.push("Stalinist One");
//     fonts.push("Stardos Stencil");
//     fonts.push("Stint Ultra Condensed");
//     fonts.push("Stint Ultra Expanded");
//     fonts.push("Stoke");
//     fonts.push("Strait");
//     fonts.push("Sue Ellen Francisco");
//     fonts.push("Sunshiney");
//     fonts.push("Supermercado One");
//     fonts.push("Suwannaphum");
//     fonts.push("Swanky and Moo Moo");
//     fonts.push("Syncopate");
//     fonts.push("Tangerine");
//     fonts.push("Taprom");
//     fonts.push("Tauri");
//     fonts.push("Teko");
//     fonts.push("Telex");
//     fonts.push("Tenor Sans");
//     fonts.push("Text Me One");
//     fonts.push("The Girl Next Door");
//     fonts.push("Tienne");
//     fonts.push("Tinos");
//     fonts.push("Titan One");
//     fonts.push("Titillium Web");
//     fonts.push("Trade Winds");
//     fonts.push("Trocchi");
//     fonts.push("Trochut");
//     fonts.push("Trykker");
//     fonts.push("Tulpen One");
//     fonts.push("Ubuntu");
//     fonts.push("Ubuntu Condensed");
//     fonts.push("Ubuntu Mono");
//     fonts.push("Ultra");
//     fonts.push("Uncial Antiqua");
//     fonts.push("Underdog");
//     fonts.push("Unica One");
//     fonts.push("UnifrakturCook");
//     fonts.push("UnifrakturMaguntia");
//     fonts.push("Unkempt");
//     fonts.push("Unlock");
//     fonts.push("Unna");
//     fonts.push("Vampiro One");
//     fonts.push("Varela");
//     fonts.push("Varela Round");
//     fonts.push("Vast Shadow");
//     fonts.push("Vibur");
//     fonts.push("Vidaloka");
//     fonts.push("Viga");
//     fonts.push("Voces");
//     fonts.push("Volkhov");
//     fonts.push("Vollkorn");
//     fonts.push("Voltaire");
//     fonts.push("VT323");
//     fonts.push("Waiting for the Sunrise");
//     fonts.push("Wallpoet");
//     fonts.push("Walter Turncoat");
//     fonts.push("Warnes");
//     fonts.push("Wellfleet");
//     fonts.push("Wendy One");
//     fonts.push("Wire One");
//     fonts.push("Yanone Kaffeesatz");
//     fonts.push("Yellowtail");
//     fonts.push("Yeseva One");
//     fonts.push("Yesteryear");
//     fonts.push("Zeyada");
//     var table = document.getElementById('font-table');
//     for (i = 0; i < fonts.length; i++) {
//         var result = d.detect(fonts[i]);
//         if(result == true) {
//             row = table.insertRow(-1);
//             col = row.insertCell(-1);
//             col.appendChild(document.createTextNode(fonts[i]))
//             col.style.fontFamily = fonts[i];
//             col = row.insertCell(-1);
//             result ? col.className = "f_green" : col.className = "f_red";
//             col.appendChild(document.createTextNode(result));
//         }
//     }
// }
// jQuery(function(){
//     font_init()
// });